# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=60)),
                ('schoolCode', models.CharField(max_length=1)),
                ('deptID', models.SmallIntegerField()),
                ('courseCode', models.CharField(max_length=5)),
                ('listOfPrereqs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('majorID', models.AutoField(primary_key=True, serialize=False)),
                ('majorName', models.CharField(max_length=60)),
                ('listOfClasses', models.TextField()),
            ],
        ),
    ]
